# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
print(torch.cuda.is_available())
# Create random tensor
random_tensor=torch.rand(7,7)
random_tensor


True


tensor([[0.9004, 0.1746, 0.3143, 0.0034, 0.2276, 0.7252, 0.9265],
        [0.7441, 0.2118, 0.8671, 0.9382, 0.0352, 0.6953, 0.4076],
        [0.2096, 0.8968, 0.0185, 0.3894, 0.2590, 0.1904, 0.0594],
        [0.4055, 0.3424, 0.3024, 0.9918, 0.2122, 0.4287, 0.7852],
        [0.1105, 0.7053, 0.3898, 0.7777, 0.9592, 0.3504, 0.5744],
        [0.8612, 0.8648, 0.8829, 0.8574, 0.8141, 0.8867, 0.8157],
        [0.0877, 0.2008, 0.1538, 0.7463, 0.9941, 0.4686, 0.0460]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
x=torch.rand(1,7)
# Perform matrix multiplication 
output=x@random_tensor
output

tensor([[0.8844, 0.7909, 0.8843, 1.1391, 0.7845, 0.9477, 0.9024]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
# Set manual seed
SEED=0
# Create two random tensors
torch.manual_seed(0)
W=torch.rand(7,7)
x=torch.rand(1,7)

# Matrix multiply tensors
Z = torch.matmul(W, x.T)




tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
SEED=1234
import torch
torch.cuda.is_available()

torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"

# Create two random tensors on GPU
a=torch.rand([2,3],device=torch.device("cpu")).to(device)
b=torch.rand([2,3], device=torch.device("cpu")).to(device)
a,b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
out=a@b.T
out,out.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [28]:
# Find max
c=out.max()
# Find min
d=out.min()
c,d

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max

e=out.argmax()
# Find arg min
f=out.argmin()
e,f

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [38]:
# Set seed

import torch
torch.manual_seed(7)
# Create random tensor
w=torch.rand([1,1,1,10])


# Remove single dimensions
sq_w=w.squeeze()

# Print out tensors and their shapes
w,w.shape
# sq_w,sq_w.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))